### ISSUE TITLE
behavior of track alignments can be very "stitchy" even when algorithm=smith-waterman; why?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#286] opened 2020-04-10 17:58 UTC
I also can't seem to change the behavior by fiddling with the threshold parameter regardless of which algorithm is specified. as an example, see:
http://dev.lis.ncgr.org:50011/epic_search/gcv/gene;vigna=vigun.IT97K-499-35.gnm1.ann2.Vigun11g013900.v1.2?algorithm=smith-waterman&match=10&mismatch=-1&gap=-1&score=30&threshold=50&bmatched=20&bintermediate=10&bmask=10&linkage=average&cthreshold=20&neighbors=50&matched=0.2&intermediate=15&sources=vigna&bregexp=&border=chromosome&regexp=&order=chromosome

![image](https://user-images.githubusercontent.com/2009605/79011956-6f062680-7b22-11ea-9494-1f686157636f.png)

You've got to give it credit for trying to find a good alignment...

**Comment by adf-ncgr** [comment] 2020-04-10 18:10
I should perhaps also note that the overly-stitchy behavior sometimes occurs when it seems the regions being aligned should not pose challenges to the faith of the aligner in the stability of genomic content, e.g.
http://dev.lis.ncgr.org:50011/epic_search/gcv/gene;vigna=vigun.IT97K-499-35.gnm1.ann2.Vigun08g065800.v1.2?algorithm=smith-waterman&match=10&mismatch=-1&gap=-1&score=30&threshold=50&bmatched=20&bintermediate=10&bmask=10&linkage=average&cthreshold=20&neighbors=50&matched=0.2&intermediate=15&sources=vigna&bregexp=&border=chromosome&regexp=&order=chromosome

![image](https://user-images.githubusercontent.com/2009605/79012713-29e2f400-7b24-11ea-893b-9ee121957842.png)

(not clear that any of these deserve stitching, but dotplots are shown for the two that seem most aggressively sewn-together in the micro-tracks)

**Comment by alancleary** [comment] 2020-04-10 18:43
This is a duplicate of issue #262, though there aren't any specific examples there. Closing this issue. Feel free to continue the discussion in #262.

**Closed by alancleary** 2020-04-10 18:43 UTC
